-- ============================================================
-- SEED: AIRPORTS
-- Reference data for major international airports.
-- Safe to re-run: ON CONFLICT (iata_code) DO NOTHING skips
-- any airports that already exist.
-- ============================================================

INSERT INTO public.airports (iata_code, airport_name, city, country_code)
VALUES
    ('IAH', 'George Bush Intercontinental Airport', 'Houston', 'US'),
    ('ATL', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta', 'US'),
    ('LAX', 'Los Angeles International Airport', 'Los Angeles', 'US'),
    ('ORD', 'O''Hare International Airport', 'Chicago', 'US'),
    ('DFW', 'Dallas/Fort Worth International Airport', 'Dallas', 'US'),
    ('DEN', 'Denver International Airport', 'Denver', 'US'),
    ('JFK', 'John F. Kennedy International Airport', 'New York', 'US'),
    ('SFO', 'San Francisco International Airport', 'San Francisco', 'US'),
    ('SEA', 'Seattle-Tacoma International Airport', 'Seattle', 'US'),
    ('LAS', 'Harry Reid International Airport', 'Las Vegas', 'US'),
    ('MIA', 'Miami International Airport', 'Miami', 'US'),
    ('EWR', 'Newark Liberty International Airport', 'Newark', 'US'),
    ('BOS', 'Logan International Airport', 'Boston', 'US'),
    ('IAD', 'Washington Dulles International Airport', 'Washington', 'US'),
    ('MCO', 'Orlando International Airport', 'Orlando', 'US'),
    ('PHL', 'Philadelphia International Airport', 'Philadelphia', 'US'),
    ('CLT', 'Charlotte Douglas International Airport', 'Charlotte', 'US'),
    ('PHX', 'Phoenix Sky Harbor International Airport', 'Phoenix', 'US'),
    ('MSP', 'Minneapolis-Saint Paul International Airport', 'Minneapolis', 'US'),
    ('DTW', 'Detroit Metropolitan Wayne County Airport', 'Detroit', 'US'),
    ('MEX', 'Mexico City International Airport', 'Mexico City', 'MX'),
    ('CUN', 'Cancun International Airport', 'Cancun', 'MX'),
    ('GDL', 'Miguel Hidalgo y Costilla Guadalajara International Airport', 'Guadalajara', 'MX'),
    ('MTY', 'Monterrey International Airport', 'Monterrey', 'MX'),
    ('TIJ', 'Tijuana International Airport', 'Tijuana', 'MX'),
    ('SJD', 'Los Cabos International Airport', 'San Jose del Cabo', 'MX'),
    ('PVR', 'Licenciado Gustavo Diaz Ordaz International Airport', 'Puerto Vallarta', 'MX'),
    ('NLU', 'Felipe Angeles International Airport', 'Mexico City', 'MX'),
    ('MID', 'Manuel Crescencio Rejon International Airport', 'Merida', 'MX'),
    ('BJX', 'Bajio International Airport', 'Leon', 'MX'),
    ('QRO', 'Queretaro International Airport', 'Queretaro', 'MX'),
    ('CJS', 'Abraham Gonzalez International Airport', 'Ciudad Juarez', 'MX'),
    ('HMO', 'General Ignacio Pesqueira Garcia International Airport', 'Hermosillo', 'MX'),
    ('CUU', 'General Roberto Fierro Villalobos International Airport', 'Chihuahua', 'MX'),
    ('ZIH', 'Ixtapa-Zihuatanejo International Airport', 'Ixtapa-Zihuatanejo', 'MX'),
    ('OAX', 'Xoxocotlan International Airport', 'Oaxaca', 'MX'),
    ('VER', 'General Heriberto Jara International Airport', 'Veracruz', 'MX'),
    ('SLP', 'Ponciano Arriaga International Airport', 'San Luis Potosi', 'MX'),
    ('AGU', 'Jesus Teran Peredo International Airport', 'Aguascalientes', 'MX'),
    ('MLM', 'General Francisco J. Mujica International Airport', 'Morelia', 'MX'),
    ('YYZ', 'Toronto Pearson International Airport', 'Toronto', 'CA'),
    ('YVR', 'Vancouver International Airport', 'Vancouver', 'CA'),
    ('YUL', 'Montreal-Trudeau International Airport', 'Montreal', 'CA'),
    ('YYC', 'Calgary International Airport', 'Calgary', 'CA'),
    ('YEG', 'Edmonton International Airport', 'Edmonton', 'CA'),
    ('YOW', 'Ottawa International Airport', 'Ottawa', 'CA'),
    ('YHZ', 'Halifax Stanfield International Airport', 'Halifax', 'CA'),
    ('YWG', 'Winnipeg James Armstrong Richardson International Airport', 'Winnipeg', 'CA'),
    ('YQB', 'Quebec City Jean Lesage International Airport', 'Quebec City', 'CA'),
    ('YHM', 'John C. Munro Hamilton International Airport', 'Hamilton', 'CA'),
    ('GRU', 'Sao Paulo/Guarulhos International Airport', 'Sao Paulo', 'BR'),
    ('BOG', 'El Dorado International Airport', 'Bogota', 'CO'),
    ('LIM', 'Jorge Chavez International Airport', 'Lima', 'PE'),
    ('SCL', 'Arturo Merino Benitez International Airport', 'Santiago', 'CL'),
    ('PTY', 'Tocumen International Airport', 'Panama City', 'PA'),
    ('BSB', 'Brasilia International Airport', 'Brasilia', 'BR'),
    ('GIG', 'Rio de Janeiro/Galeao International Airport', 'Rio de Janeiro', 'BR'),
    ('EZE', 'Ministro Pistarini International Airport', 'Buenos Aires', 'AR'),
    ('MDE', 'Jose Maria Cordova International Airport', 'Medellin', 'CO'),
    ('CNF', 'Belo Horizonte International Airport', 'Belo Horizonte', 'BR'),
    ('AEP', 'Jorge Newbery International Airport', 'Buenos Aires', 'AR'),
    ('UIO', 'Mariscal Sucre International Airport', 'Quito', 'EC'),
    ('GYE', 'Jose Joaquin de Olmedo International Airport', 'Guayaquil', 'EC'),
    ('SJO', 'Juan Santamaria International Airport', 'San Jose', 'CR'),
    ('SAL', 'El Salvador International Airport', 'San Salvador', 'SV'),
    ('GUA', 'La Aurora International Airport', 'Guatemala City', 'GT'),
    ('CLO', 'Alfonso Bonilla Aragon International Airport', 'Cali', 'CO'),
    ('CTG', 'Rafael Nunez International Airport', 'Cartagena', 'CO'),
    ('MVD', 'Carrasco International Airport', 'Montevideo', 'UY'),
    ('ASU', 'Silvio Pettirossi International Airport', 'Asuncion', 'PY'),
    ('VVI', 'Viru Viru International Airport', 'Santa Cruz de la Sierra', 'BO'),
    ('POA', 'Salgado Filho International Airport', 'Porto Alegre', 'BR'),
    ('FLN', 'Hercilio Luz International Airport', 'Florianopolis', 'BR'),
    ('LIR', 'Daniel Oduber Quiros International Airport', 'Liberia', 'CR'),
    ('SAP', 'Ramon Villeda Morales International Airport', 'San Pedro Sula', 'HN'),
    ('LHR', 'Heathrow Airport', 'London', 'GB'),
    ('LGW', 'Gatwick Airport', 'London', 'GB'),
    ('CDG', 'Charles de Gaulle Airport', 'Paris', 'FR'),
    ('ORY', 'Paris Orly Airport', 'Paris', 'FR'),
    ('AMS', 'Amsterdam Airport Schiphol', 'Amsterdam', 'NL'),
    ('FRA', 'Frankfurt Airport', 'Frankfurt', 'DE'),
    ('MUC', 'Munich Airport', 'Munich', 'DE'),
    ('ZRH', 'Zurich Airport', 'Zurich', 'CH'),
    ('GVA', 'Geneva Airport', 'Geneva', 'CH'),
    ('BRU', 'Brussels Airport', 'Brussels', 'BE'),
    ('LUX', 'Luxembourg Airport', 'Luxembourg', 'LU'),
    ('DUB', 'Dublin Airport', 'Dublin', 'IE'),
    ('MAN', 'Manchester Airport', 'Manchester', 'GB'),
    ('EDI', 'Edinburgh Airport', 'Edinburgh', 'GB'),
    ('CPH', 'Copenhagen Airport', 'Copenhagen', 'DK'),
    ('OSL', 'Oslo Airport', 'Oslo', 'NO'),
    ('ARN', 'Stockholm Arlanda Airport', 'Stockholm', 'SE'),
    ('HEL', 'Helsinki Airport', 'Helsinki', 'FI'),
    ('VIE', 'Vienna International Airport', 'Vienna', 'AT'),
    ('LIS', 'Humberto Delgado Airport', 'Lisbon', 'PT'),
    ('OPO', 'Francisco Sa Carneiro Airport', 'Porto', 'PT'),
    ('BCN', 'Barcelona-El Prat Airport', 'Barcelona', 'ES'),
    ('MAD', 'Adolfo Suarez Madrid-Barajas Airport', 'Madrid', 'ES'),
    ('AGP', 'Malaga-Costa del Sol Airport', 'Malaga', 'ES'),
    ('PMI', 'Palma de Mallorca Airport', 'Palma de Mallorca', 'ES'),
    ('WAW', 'Warsaw Chopin Airport', 'Warsaw', 'PL'),
    ('KRK', 'John Paul II International Airport Krakow-Balice', 'Krakow', 'PL'),
    ('BUD', 'Budapest Ferenc Liszt International Airport', 'Budapest', 'HU'),
    ('PRG', 'Vaclav Havel Airport Prague', 'Prague', 'CZ'),
    ('OTP', 'Henri Coanda International Airport', 'Bucharest', 'RO'),
    ('SOF', 'Sofia Airport', 'Sofia', 'BG'),
    ('BEG', 'Belgrade Nikola Tesla Airport', 'Belgrade', 'RS'),
    ('ZAG', 'Zagreb Airport', 'Zagreb', 'HR'),
    ('LJU', 'Ljubljana Joze Pucnik Airport', 'Ljubljana', 'SI'),
    ('TIA', 'Tirana International Airport Nene Tereza', 'Tirana', 'AL'),
    ('SKP', 'Skopje International Airport', 'Skopje', 'MK'),
    ('SJJ', 'Sarajevo International Airport', 'Sarajevo', 'BA'),
    ('TGD', 'Podgorica Airport', 'Podgorica', 'ME'),
    ('RIX', 'Riga International Airport', 'Riga', 'LV'),
    ('VNO', 'Vilnius International Airport', 'Vilnius', 'LT'),
    ('TLL', 'Tallinn Airport', 'Tallinn', 'EE'),
    ('KIV', 'Chisinau International Airport', 'Chisinau', 'MD'),
    ('ATH', 'Athens International Airport', 'Athens', 'GR'),
    ('SKG', 'Thessaloniki Airport Makedonia', 'Thessaloniki', 'GR'),
    ('RHO', 'Rhodes International Airport', 'Rhodes', 'GR'),
    ('HER', 'Heraklion International Airport', 'Heraklion', 'GR'),
    ('CFU', 'Corfu International Airport', 'Corfu', 'GR'),
    ('KGS', 'Kos International Airport', 'Kos', 'GR'),
    ('DBV', 'Dubrovnik Airport', 'Dubrovnik', 'HR'),
    ('SPU', 'Split Airport', 'Split', 'HR'),
    ('HND', 'Tokyo Haneda Airport', 'Tokyo', 'JP'),
    ('NRT', 'Narita International Airport', 'Tokyo', 'JP'),
    ('ICN', 'Incheon International Airport', 'Seoul', 'KR'),
    ('GMP', 'Gimpo International Airport', 'Seoul', 'KR'),
    ('PEK', 'Beijing Capital International Airport', 'Beijing', 'CN'),
    ('PKX', 'Beijing Daxing International Airport', 'Beijing', 'CN'),
    ('PVG', 'Shanghai Pudong International Airport', 'Shanghai', 'CN'),
    ('SHA', 'Shanghai Hongqiao International Airport', 'Shanghai', 'CN'),
    ('CAN', 'Guangzhou Baiyun International Airport', 'Guangzhou', 'CN'),
    ('SZX', 'Shenzhen Baoan International Airport', 'Shenzhen', 'CN'),
    ('HKG', 'Hong Kong International Airport', 'Hong Kong', 'HK'),
    ('TPE', 'Taiwan Taoyuan International Airport', 'Taipei', 'TW'),
    ('SIN', 'Singapore Changi Airport', 'Singapore', 'SG'),
    ('BKK', 'Suvarnabhumi Airport', 'Bangkok', 'TH'),
    ('DMK', 'Don Mueang International Airport', 'Bangkok', 'TH'),
    ('KUL', 'Kuala Lumpur International Airport', 'Kuala Lumpur', 'MY'),
    ('CGK', 'Soekarno-Hatta International Airport', 'Jakarta', 'ID'),
    ('MNL', 'Ninoy Aquino International Airport', 'Manila', 'PH'),
    ('DEL', 'Indira Gandhi International Airport', 'New Delhi', 'IN'),
    ('BOM', 'Chhatrapati Shivaji Maharaj International Airport', 'Mumbai', 'IN'),
    ('BLR', 'Kempegowda International Airport', 'Bengaluru', 'IN'),
    ('MAA', 'Chennai International Airport', 'Chennai', 'IN'),
    ('SGN', 'Tan Son Nhat International Airport', 'Ho Chi Minh City', 'VN'),
    ('HAN', 'Noi Bai International Airport', 'Hanoi', 'VN'),
    ('KIX', 'Kansai International Airport', 'Osaka', 'JP'),
    ('DXB', 'Dubai International Airport', 'Dubai', 'AE'),
    ('DWC', 'Al Maktoum International Airport', 'Dubai', 'AE'),
    ('AUH', 'Zayed International Airport', 'Abu Dhabi', 'AE'),
    ('SHJ', 'Sharjah International Airport', 'Sharjah', 'AE'),
    ('DOH', 'Hamad International Airport', 'Doha', 'QA'),
    ('RUH', 'King Khalid International Airport', 'Riyadh', 'SA'),
    ('JED', 'King Abdulaziz International Airport', 'Jeddah', 'SA'),
    ('DMM', 'King Fahd International Airport', 'Dammam', 'SA'),
    ('MED', 'Prince Mohammad bin Abdulaziz International Airport', 'Medina', 'SA'),
    ('BAH', 'Bahrain International Airport', 'Manama', 'BH'),
    ('MCT', 'Muscat International Airport', 'Muscat', 'OM'),
    ('KWI', 'Kuwait International Airport', 'Kuwait City', 'KW'),
    ('TLV', 'Ben Gurion Airport', 'Tel Aviv', 'IL'),
    ('AMM', 'Queen Alia International Airport', 'Amman', 'JO'),
    ('BEY', 'Beirut-Rafic Hariri International Airport', 'Beirut', 'LB'),
    ('BGW', 'Baghdad International Airport', 'Baghdad', 'IQ'),
    ('EBL', 'Erbil International Airport', 'Erbil', 'IQ'),
    ('IKA', 'Imam Khomeini International Airport', 'Tehran', 'IR'),
    ('THR', 'Mehrabad International Airport', 'Tehran', 'IR'),
    ('ESB', 'Esenboga Airport', 'Ankara', 'TR'),
    ('IST', 'Istanbul Airport', 'Istanbul', 'TR'),
    ('SAW', 'Sabiha Gokcen International Airport', 'Istanbul', 'TR'),
    ('ADB', 'Izmir Adnan Menderes Airport', 'Izmir', 'TR'),
    ('AYT', 'Antalya Airport', 'Antalya', 'TR'),
    ('LCA', 'Larnaca International Airport', 'Larnaca', 'CY'),
    ('SYD', 'Sydney Kingsford Smith Airport', 'Sydney', 'AU'),
    ('MEL', 'Melbourne Airport', 'Melbourne', 'AU'),
    ('BNE', 'Brisbane Airport', 'Brisbane', 'AU'),
    ('PER', 'Perth Airport', 'Perth', 'AU'),
    ('ADL', 'Adelaide Airport', 'Adelaide', 'AU'),
    ('CNS', 'Cairns Airport', 'Cairns', 'AU'),
    ('OOL', 'Gold Coast Airport', 'Gold Coast', 'AU'),
    ('AKL', 'Auckland Airport', 'Auckland', 'NZ'),
    ('CHC', 'Christchurch Airport', 'Christchurch', 'NZ'),
    ('WLG', 'Wellington Airport', 'Wellington', 'NZ'),
    ('NAN', 'Nadi International Airport', 'Nadi', 'FJ'),
    ('POM', 'Jacksons International Airport', 'Port Moresby', 'PG'),
    ('GUM', 'Antonio B. Won Pat International Airport', 'Guam', 'GU'),
    ('PPT', 'Fa''a''a International Airport', 'Papeete', 'PF'),
    ('APW', 'Faleolo International Airport', 'Apia', 'WS'),
    ('SAN', 'San Diego International Airport', 'San Diego', 'US'),
    ('BNA', 'Nashville International Airport', 'Nashville', 'US'),
    ('AUS', 'Austin-Bergstrom International Airport', 'Austin', 'US'),
    ('SLC', 'Salt Lake City International Airport', 'Salt Lake City', 'US'),
    ('RDU', 'Raleigh-Durham International Airport', 'Raleigh', 'US'),
    ('TPA', 'Tampa International Airport', 'Tampa', 'US'),
    ('STL', 'St. Louis Lambert International Airport', 'St. Louis', 'US'),
    ('BWI', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore', 'US'),
    ('HNL', 'Daniel K. Inouye International Airport', 'Honolulu', 'US'),
    ('ANC', 'Ted Stevens Anchorage International Airport', 'Anchorage', 'US'),
    ('YXE', 'Saskatoon John G. Diefenbaker International Airport', 'Saskatoon', 'CA'),
    ('YQR', 'Regina International Airport', 'Regina', 'CA'),
    ('TQO', 'Tulum International Airport', 'Tulum', 'MX'),
    ('TRC', 'Francisco Sarabia International Airport', 'Torreon', 'MX'),
    ('TAM', 'General Francisco Javier Mina International Airport', 'Tampico', 'MX'),
    ('CZM', 'Cozumel International Airport', 'Cozumel', 'MX'),
    ('MZT', 'General Rafael Buelna International Airport', 'Mazatlan', 'MX'),
    ('TGZ', 'Angel Albino Corzo International Airport', 'Tuxtla Gutierrez', 'MX'),
    ('FCO', 'Leonardo da Vinci-Fiumicino Airport', 'Rome', 'IT'),
    ('MXP', 'Milan Malpensa Airport', 'Milan', 'IT'),
    ('LIN', 'Milan Linate Airport', 'Milan', 'IT'),
    ('NAP', 'Naples International Airport', 'Naples', 'IT'),
    ('VCE', 'Venice Marco Polo Airport', 'Venice', 'IT'),
    ('PSA', 'Pisa International Airport', 'Pisa', 'IT'),
    ('KEF', 'Keflavik International Airport', 'Reykjavik', 'IS'),
    ('BRS', 'Bristol Airport', 'Bristol', 'GB'),
    ('NCL', 'Newcastle International Airport', 'Newcastle', 'GB'),
    ('GDN', 'Gdansk Lech Walesa Airport', 'Gdansk', 'PL'),
    ('CAI', 'Cairo International Airport', 'Cairo', 'EG'),
    ('SSH', 'Sharm El Sheikh International Airport', 'Sharm El Sheikh', 'EG'),
    ('HRG', 'Hurghada International Airport', 'Hurghada', 'EG'),
    ('TBS', 'Tbilisi International Airport', 'Tbilisi', 'GE'),
    ('CTU', 'Chengdu Shuangliu International Airport', 'Chengdu', 'CN'),
    ('TFU', 'Chengdu Tianfu International Airport', 'Chengdu', 'CN'),
    ('XIY', 'Xi''an Xianyang International Airport', 'Xi''an', 'CN'),
    ('HGH', 'Hangzhou Xiaoshan International Airport', 'Hangzhou', 'CN'),
    ('XMN', 'Xiamen Gaoqi International Airport', 'Xiamen', 'CN'),
    ('KMG', 'Kunming Changshui International Airport', 'Kunming', 'CN'),
    ('NGO', 'Chubu Centrair International Airport', 'Nagoya', 'JP'),
    ('FUK', 'Fukuoka Airport', 'Fukuoka', 'JP'),
    ('HKT', 'Phuket International Airport', 'Phuket', 'TH'),
    ('CNX', 'Chiang Mai International Airport', 'Chiang Mai', 'TH'),
    ('DPS', 'I Gusti Ngurah Rai International Airport', 'Denpasar', 'ID'),
    ('CEB', 'Mactan-Cebu International Airport', 'Cebu', 'PH'),
    ('HYD', 'Rajiv Gandhi International Airport', 'Hyderabad', 'IN'),
    ('CCU', 'Netaji Subhas Chandra Bose International Airport', 'Kolkata', 'IN'),
    ('DRW', 'Darwin International Airport', 'Darwin', 'AU'),
    ('HBA', 'Hobart International Airport', 'Hobart', 'AU'),
    ('JNB', 'O.R. Tambo International Airport', 'Johannesburg', 'ZA'),
    ('CPT', 'Cape Town International Airport', 'Cape Town', 'ZA'),
    ('DUR', 'King Shaka International Airport', 'Durban', 'ZA'),
    ('ADD', 'Addis Ababa Bole International Airport', 'Addis Ababa', 'ET'),
    ('NBO', 'Jomo Kenyatta International Airport', 'Nairobi', 'KE'),
    ('CMN', 'Mohammed V International Airport', 'Casablanca', 'MA'),
    ('RAK', 'Marrakesh Menara Airport', 'Marrakesh', 'MA'),
    ('TUN', 'Tunis-Carthage International Airport', 'Tunis', 'TN'),
    ('PUJ', 'Punta Cana International Airport', 'Punta Cana', 'DO'),
    ('MBJ', 'Sangster International Airport', 'Montego Bay', 'JM'),
    ('NAS', 'Lynden Pindling International Airport', 'Nassau', 'BS'),
    ('AUA', 'Queen Beatrix International Airport', 'Oranjestad', 'AW'),
    ('CUR', 'Curacao International Airport', 'Willemstad', 'CW'),
    ('SXM', 'Princess Juliana International Airport', 'Sint Maarten', 'SX')
ON CONFLICT (iata_code) DO NOTHING;