-- ============================================================
-- SEED: BRANDS
-- Safe to re-run: ON CONFLICT (name) DO NOTHING skips brands
-- that already exist (name is UNIQUE per schema).
-- ============================================================

INSERT INTO public.brands (name) VALUES
    ('Chanel'),
    ('Dior'),
    ('Johnnie Walker'),
    ('Marlboro'),
    ('Armand de Brignac'),
    ('Dom Pérignon'),
    ('Chivas Regal'),
    ('Hermès'),
    ('Louis Vuitton'),
    ('Gucci'),
    ('Saint Laurent'),
    ('Prada'),
    ('Bulgari'),
    ('Burberry'),
    ('Cartier'),
    ('Sobranie'),
    ('Giorgio Armani'),
    ('Yves Saint Laurent'),
    ('Versace'),
    ('Tom Ford'),
    ('Maison Francis Kurkdjian'),
    ('Creed'),
    ('Jo Malone London'),
    ('Le Labo'),
    ('Byredo'),
    ('Maison Margiela'),
    ('Dolce & Gabbana'),
    ('Valentino'),
    ('Givenchy'),
    ('Calvin Klein'),
    ('Jean Paul Gaultier'),
    ('Paco Rabanne'),
    ('Viktor & Rolf'),
    ('Lancome'),
    ('Clinique'),
    ('Narciso Rodriguez'),
    ('Azzaro'),
    ('Montblanc'),
    ('Issey Miyake'),
    ('1800 Tequila'),
    ('1921'),
    ('400 Conejos'),
    ('Absolut'),
    ('Adiccion'),
    ('Amaras'),
    ('Amarula'),
    ('Bacardi'),
    ('Baileys'),
    ('Baluarte'),
    ('Belvedere'),
    ('Bombay Sapphire'),
    ('Botran'),
    ('Bottega'),
    ('Buchanan'),
    ('Campari'),
    ('Captain Morgan'),
    ('Casa Dragones'),
    ('Casamigos'),
    ('Chita'),
    ('Cîroc'),
    ('Codigo'),
    ('Cointreau'),
    ('Corralejo'),
    ('Creyente'),
    ('Crown Royal'),
    ('Dewar''''s'),
    ('Don Julio'),
    ('Don Ramón'),
    ('El Jimador'),
    ('El Recuerdo'),
    ('El Señorio'),
    ('Flor de Caña'),
    ('Folgado'),
    ('Glen Deveron'),
    ('Glenfiddich'),
    ('Glenmorangie'),
    ('Gran Centenario'),
    ('Gran Malo'),
    ('Grand Marnier'),
    ('Grey Goose'),
    ('Havana Club'),
    ('Hendrick''''s'),
    ('Hennessy'),
    ('Herradura'),
    ('Hibiki'),
    ('Iztic'),
    ('Jack Daniel''''s'),
    ('Jägermeister'),
    ('Jameson'),
    ('Jim Beam'),
    ('José Cuervo'),
    ('Kahlúa'),
    ('Lanson'),
    ('Laphroaig'),
    ('Licor 43'),
    ('Maestro Dobel'),
    ('Maestro Dobel 50'),
    ('Maker''''s Mark'),
    ('Malibu'),
    ('María Tepoztlán'),
    ('Martell'),
    ('Mitre'),
    ('Moët & Chandon'),
    ('Montelobos'),
    ('Ojo de Tigre'),
    ('Old Parr'),
    ('Olmeca'),
    ('Patrón'),
    ('Picaro'),
    ('Rémy Martin'),
    ('Revolución'),
    ('Royal Salute'),
    ('Sauza'),
    ('Sheridan''''s'),
    ('Suntory'),
    ('Talisker'),
    ('Tanqueray'),
    ('Tequila Ocho'),
    ('Tequila Tres Generaciones'),
    ('Tequipal'),
    ('Tequitime'),
    ('The Glenlivet'),
    ('Tito''''s'),
    ('Torres'),
    ('Veuve Clicquot'),
    ('Volcan de Mi Tierra'),
    ('Xicote'),
    ('Zacapa'),
    ('Zignum'),
    ('Camel'),
    ('Lucky Strike'),
    ('Parliament'),
    ('Winston'),
    ('Kent'),
    ('Dunhill'),
    ('Rothmans'),
    ('Pall Mall'),
    ('L&M'),
    ('Chesterfield'),
    ('Benson & Hedges'),
    ('Davidoff'),
    ('Vogue'),
    ('West'),
    ('Mevius'),
    ('Seven Stars'),
    ('Mild Seven'),
    ('Esse'),
    ('Gauloises'),
    ('Gitanes'),
    ('John Player Special'),
    ('Silk Cut'),
    ('Winfield')
ON CONFLICT (name) DO NOTHING;