"""
dft/helpers/populate_airport_geo.py

Cross-references your airports table (exported as CSV) against the free
OurAirports dataset (https://ourairports.com/data/) to find latitude/
longitude for each airport by IATA code, then generates a SQL file with
UPDATE statements you can review and run against Supabase.

SETUP:
1. In the Supabase SQL editor, run:
       SELECT id, iata_code FROM airports ORDER BY iata_code;
   Export the result as CSV and save it as:
       dft/helpers/data/current_airports.csv

2. Run this script:
       python3 dft/helpers/populate_airport_geo.py

3. It downloads the latest OurAirports CSV (cached locally after first run),
   matches each of your airports by IATA code, and writes:
       dft/helpers/data/airports_geo_update.sql

4. Review that SQL file, then run it against your Supabase database
   (SQL editor, or psql, or however you normally run migrations).

5. It will also print a list of any IATA codes it could NOT match, so you
   can look those up manually and add them by hand.
"""

import csv
import io
import urllib.request
from pathlib import Path

HELPERS_DIR = Path(__file__).resolve().parent
DATA_DIR = HELPERS_DIR / "data"

CURRENT_AIRPORTS_CSV = DATA_DIR / "current_airports.csv"
OURAIRPORTS_CACHE = DATA_DIR / "ourairports_cache.csv"
OUTPUT_SQL = DATA_DIR / "airports_geo_update.sql"

OURAIRPORTS_URL = "https://davidmegginson.github.io/ourairports-data/airports.csv"


def download_ourairports_data() -> str:
    """Download (or use cached copy of) the OurAirports dataset."""
    if OURAIRPORTS_CACHE.exists():
        print(f"Using cached OurAirports data at {OURAIRPORTS_CACHE}")
        return OURAIRPORTS_CACHE.read_text(encoding="utf-8")

    print(f"Downloading OurAirports data from {OURAIRPORTS_URL} ...")
    with urllib.request.urlopen(OURAIRPORTS_URL) as response:
        content = response.read().decode("utf-8")

    DATA_DIR.mkdir(parents=True, exist_ok=True)
    OURAIRPORTS_CACHE.write_text(content, encoding="utf-8")
    print(f"Cached to {OURAIRPORTS_CACHE} for future runs.")
    return content


def build_iata_lookup(ourairports_csv_text: str) -> dict:
    """Build a dict of iata_code -> (latitude, longitude) from OurAirports data."""
    lookup = {}
    reader = csv.DictReader(io.StringIO(ourairports_csv_text))
    for row in reader:
        iata = (row.get("iata_code") or "").strip().upper()
        if not iata:
            continue
        lat = row.get("latitude_deg")
        lon = row.get("longitude_deg")
        if not lat or not lon:
            continue
        lookup[iata] = (lat, lon)
    return lookup


def load_current_airports() -> list:
    """Read your exported airports CSV: expects columns id, iata_code."""
    if not CURRENT_AIRPORTS_CSV.exists():
        raise FileNotFoundError(
            f"Could not find {CURRENT_AIRPORTS_CSV}. "
            f"Export your airports table (id, iata_code) as CSV and save it there first."
        )

    with open(CURRENT_AIRPORTS_CSV, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        return [
            {"id": row["id"], "iata_code": row["iata_code"].strip().upper()}
            for row in reader
        ]


def generate_sql(current_airports: list, iata_lookup: dict) -> tuple:
    matched_lines = []
    unmatched = []

    for airport in current_airports:
        iata = airport["iata_code"]
        coords = iata_lookup.get(iata)

        if not coords:
            unmatched.append(iata)
            continue

        lat, lon = coords
        matched_lines.append(
            f"UPDATE airports SET latitude = {lat}, longitude = {lon} "
            f"WHERE iata_code = '{iata}';"
        )

    return matched_lines, unmatched


def main():
    ourairports_text = download_ourairports_data()
    iata_lookup = build_iata_lookup(ourairports_text)
    current_airports = load_current_airports()

    print(f"\nLoaded {len(current_airports)} airports from {CURRENT_AIRPORTS_CSV}")
    print(f"OurAirports dataset has {len(iata_lookup)} airports with IATA codes\n")

    matched_lines, unmatched = generate_sql(current_airports, iata_lookup)

    with open(OUTPUT_SQL, "w", encoding="utf-8") as f:
        f.write("-- Auto-generated by populate_airport_geo.py\n")
        f.write("-- Review before running against your database.\n\n")
        f.write("\n".join(matched_lines))
        f.write("\n")

    print(f"✓ Matched {len(matched_lines)} airports")
    print(f"✓ Wrote SQL to {OUTPUT_SQL}\n")

    if unmatched:
        print(f"⚠ Could not match {len(unmatched)} airports (no IATA match in OurAirports data):")
        for code in unmatched:
            print(f"  - {code}")
        print("\nYou'll need to look these up manually and add UPDATE statements by hand.")
    else:
        print("All airports matched successfully.")


if __name__ == "__main__":
    main()